public enum AccountType {
    SAVINGS_ACCOUNT,
    CHECKING_ACCOUNT,
    CERTIFICATE_OF_DEPOSIT_ACCOUNT,
    MONEY_MARKET_ACCOUNT,
    INDIVIDUAL_RETIREMENT_ACCOUNT,
    JOINT_ACCOUNT,
    BUSINESS_ACCOUNT,
    STUDENT_ACCOUNT,
    TRUST_ACCOUNT,
    HIGH_YIELD_SAVINGS_ACCOUNT
}
